#pragma once

namespace Client
{
	enum class PLAYER_ANIM { HANDGUN = 0, NONE = 1, KNIFE = 2 , SHOTGUN = 3, SNIPER = 4, WEAPONCHANGE = 5, END };
		
	enum class STATE_ANIM { START, LOOP, LOOP2, END };

	enum class COLLISION_LAYER { PLAYER = 0, PLAYER_VIEW, RAY, MONSTER , ITEM, KNIFE, WEAPON, TRIGGER_PLAYER, TRIGGER_MON, RESIST, END};
	
	enum class OBJECT_TYPE { PLAYER, PLAYER_VIEW, RAY,
							RESIST,ATTACK, CHASE,
							MON_HEAD, MON_BODY, MON_SHOULDER_L, MON_SHOULDER_R,
							ITEM, ITEM_DETACT, WEAPON, EVENT, END };

	enum class DIRECTION { F, FR, R, BR, B, BL, L, FL, END};

	enum class TRIGGER_TYPE { PLAYER, MONSTER, END };

}

